services:
  elmo.api:
    image: elmo.api:latest
    container_name: elmo.api
    restart: unless-stopped
    networks:
      - elmo
    env_file:
      - './env.local'

networks:
  elmo:
    external: true
