services:
  elmo.nginx:
    image: nginx:1.24.0
    container_name: elmo.nginx
    restart: unless-stopped
    networks:
      - elmo
    ports:
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
    environment:
      TZ: Asia/Taipei


networks:
  elmo:
    external: true
